---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(janitor)
library(stringr)
```


```{r}
data3 <- read_excel("data/candy_ranking_data/boing-boing-candy-2017.xlsx")
```


```{r}
names(data3)
```

```{r}
clean_data3 <- data3 %>% 
                clean_names() %>% 
                mutate(id = row_number(),
                       year = "2017") %>% 
                unite("year_id", year, id) %>% 
                pivot_longer(7:109,
                             names_to = "sweets",
                             values_to = "rating") %>% 
                rename("age" = "q3_age",
                       "gender" = "q2_gender",
                       "country"= "q4_country",
                       "trick_or_treating" = "q1_going_out") %>% 
                select(year_id, age, gender, trick_or_treating, sweets, rating, country) %>% 
                mutate(age = as.numeric(age)) %>% 
                filter(age > 0 & age < 120)

clean_data3
                
```



```{r}
# avg_age going trick_or_treating

clean_data3 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "Yes") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(avg_age = mean(age))
```

```{r}
# number of people trick_or_treating

clean_data3 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "Yes") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(count = nrow(.))
```

```{r}
# avg_age not trick_or_treating

clean_data3 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "No") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(avg_age = mean(age))
```

```{r}
# number of people not trick_or_treating

clean_data3 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "No") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(count = nrow(.))
```

```{r}
# checking if missing any ages

clean_data3 %>% 
  group_by(year_id, age) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  summarise(count = nrow(.))
```

```{r}
# Number per rating of each sweet

clean_data3 %>% 
  group_by(sweets, rating) %>% 
  summarise(count = n())
```

```{r}
# number per gender

clean_data3 %>% 
  group_by(year_id, gender) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(gender) %>% 
  summarise(count = n())
```

```{r}
# test_data3 <- data3 %>% 
#                 clean_names() %>% 
#                 mutate(id = row_number(),
#                        year = "2017") %>% 
#                 unite("year_id", year, id) %>% 
#                 pivot_longer(7:109,
#                              names_to = "sweets",
#                              values_to = "rating") %>% 
#                 rename("age" = "q3_age",
#                        "gender" = "q2_gender",
#                        "country"= "q4_country",
#                        "trick_or_treating" = "q1_going_out") %>% 
#                 select(year_id, age, gender, trick_or_treating, sweets, rating, country)
```


```{r}
# Age question inputs

clean_data3 %>% 
  group_by(year_id, age) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(age) %>% 
  summarise(count = n())
```


```{r}
# Age question inputs after cleaning

clean_data3 %>% 
  group_by(year_id, age) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(age) %>% 
  summarise(count = n())
```





```{r}
# country cleaning

country_data3 <- data3 %>% 
                clean_names() %>% 
                mutate(id = row_number(),
                       year = "2017") %>% 
                unite("year_id", year, id) %>% 
                pivot_longer(7:107,
                             names_to = "sweets",
                             values_to = "rating") %>%
                rename("age" = "q3_age",
                       "gender" = "q2_gender",
                       "country"= "q4_country",
                       "trick_or_treating" = "q1_going_out") %>% 
                select(year_id, age, gender, trick_or_treating, 
                       sweets, rating, country)

country_data3
```


```{r}
# country checking

country_data3 %>% 
  group_by(year_id, country) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(country) %>% 
  summarise(count = n())
```


```{r}
country_clean_data3 <- clean_data3 %>% 
                        mutate(country = str_to_lower(country))

country_clean_data3 <- country_clean_data3 %>%
  mutate(
         country = if_else(str_detect(country, "united states"), "US", country),
         country = if_else(str_detect(country, "us"), "US", country),
         country = if_else(str_detect(country, "usa"), "US", country),
         country = if_else(str_detect(country, "u.s.a."), "US", country),
         country = if_else(str_detect(country, "u s a"), "US", country),
         country = if_else(str_detect(country, "murica"), "US", country),
         country = if_else(str_detect(country, "murrika"), "US", country),
         country = if_else(str_detect(country, "california"), "US", country),
         country = if_else(str_detect(country, "alaska"), "US", country),
         country = if_else(str_detect(country, "'merica"), "US", country),
         country = if_else(str_detect(country, "new jersey"), "US", country),
         country = if_else(str_detect(country, "new york"), "US", country),
         country = if_else(str_detect(country, "trumpistan"), "US", country),
         country = if_else(str_detect(country, "ud"), "US", country),
         country = if_else(str_detect(country, "unite states"), "US", country),
         country = if_else(str_detect(country, "unied states"), "US", country),
         country = if_else(str_detect(country, "united state"), "US", country),
         country = if_else(str_detect(country, "united statea"), "US", country),
         country = if_else(str_detect(country, "'north carolina"), "US", country),
         country = if_else(str_detect(country, "united stated"), "US", country),
         country = if_else(str_detect(country, "us of a"), "US", country),
         country = if_else(str_detect(country, "usaa"), "US", country),
         country = if_else(str_detect(country, "ussa"), "US", country),
         country = if_else(str_detect(country, "usausausa"), "US", country),
         country = if_else(str_detect(country, "pittsburgh"), "US", country),
         country = if_else(str_detect(country, "u s"), "US", country),
         country = if_else(str_detect(country, "u.s."), "US", country),
         country = if_else(str_detect(country, "unhinged states"), "US", country),
         country = if_else(str_detect(country, "united sates"), "US", country),
         country = if_else(str_detect(country, "united staes"), "US", country),
         country = if_else(str_detect(country, "united statss"), "US", country),
         country = if_else(str_detect(country, "united ststes"), "US", country),
         country = if_else(str_detect(country, "unites states"), "US", country),
         country = if_else(str_detect(country, "america"), "US", country),
         country = if_else(str_detect(country, "ahem....amerca"), "US", country)
         ) %>% 

         
         
         
  mutate(country = str_trim(country, side = "both"),    # Change to Uk
         country = str_squish(country),
         country = str_replace_all(country, "england", "UK"),
         country = str_replace_all(country, "endland", "UK"),
         country = str_replace_all(country, "scotland", "UK"),
         country = str_replace_all(country, "[u][k]", "UK"),
         country = str_replace_all(country, "u.k.", "UK"),
         country = str_replace_all(country, "[uU]nited [kK]ingdom", "UK")
        ) %>%
  mutate(country = str_replace_all(country, "canae", "Unknow Country")
        ) %>% 
  mutate(country = str_trim(country, side = "both"),    # Change to Canada
         country = str_squish(country),
         country = str_replace_all(country, "[cC]anada", "Canada"),
         country = str_replace_all(country, "can", "Canada")
        ) %>%
  mutate(country = if_else(str_detect(country, "Canada`"), 
                           "Canada", country)) %>% 


  mutate(country = if_else(str_detect(country,   # change to Unknown Country
                          "atlantis"), "Unknown Country", country),
         country = if_else(str_detect(country, 
                          "fear and loathing"), "Unknown Country", country),
         country = if_else(str_detect(country, 
                          "i don't know anymore"), "Unknown Country", country),
         country = if_else(str_detect(country, 
                          "insanity lately"), "Unknown Country", country),
         country = if_else(str_detect(country, 
                           "narnia"), "Unknown Country", country),
         country = if_else(str_detect(country, 
                           "soviet CanadaUKstan"), "Unknown Country", country),
         country = if_else(str_detect(country, 
                            "[0-9]|[0-9][0-9]"), "Unknown Country", country)


                              ) %>% 

  mutate(country = if_else(str_detect(country, "US") |   # change to rest of world
                           str_detect(country, "UK") |
                           str_detect(country, "Canada") |
                           str_detect(country, "Unknown Country") |
                           is.na(country),
                           country, "all other countries")
                           ) 
country_clean_data3
```


```{r}
country_clean_data3 %>% 
  group_by(year_id, country) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(country) %>% 
  summarise(count = n())
```



```{r}
write_csv(country_clean_data3, "data/data_cleaned_2017.csv")
```

