---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(janitor)
```

```{r}
data1 <- read_excel(here(
  "raw_data/candy_ranking_data/boing-boing-candy-2015.xlsx"))
data2 <- read_excel(here(
  "raw_data/candy_ranking_data/boing-boing-candy-2016.xlsx"))
data3 <- read_excel(here(
  "raw_data/candy_ranking_data/boing-boing-candy-2017.xlsx"))
```

```{r}
names(data1)
class(data1)
head(data1)
```


```{r}
names(data2)
class(data2)
head(data2)
```

```{r}
names(data3)
class(data3)
head(data3)
```


```{r}
clean_data1 <- data1 %>% 
                clean_names() %>% 
                mutate(id = row_number(),
                       year = "2015") %>% 
                unite("year_id", year, id) %>% 
                pivot_longer(c(4:15, 17:37, 39:62, 64:93, 96, 114, 115),
                             names_to = "sweets",
                             values_to = "rating") %>% 
  
                # Don't use not needed
                # pivot_longer(starts_with("please_estimate"),
                #              names_to = "celebrities",
                #              values_to = "degree_of_separation") %>%
                rename("age" = "how_old_are_you",
                              "trick_or_treating" = 
                "are_you_going_actually_going_trick_or_treating_yourself") %>% 
                mutate(gender = NA_character_) %>% 
                mutate(country = NA_character_) %>%
                select(year_id, age, gender, trick_or_treating, sweets, 
                       rating, country) %>% 
                mutate(age = as.numeric(age)) %>% 
                filter(age > 0 & age < 120)
                
  
  
  
               # mutate(trick_or_treating = is.logical(trick_or_treating))

head(clean_data1, 30)
#names(clean_data1)
```

```{r}
age_is_null <- clean_data1 %>% 
                  filter(age == is.null(age))
age_is_null
```


```{r}
# avg_age going trick_or_treating

clean_data1 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "Yes") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(avg_age = mean(age))
```

```{r}
# number of people trick_or_treating

clean_data1 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "Yes") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(count = nrow(.))
```


```{r}
# avg_age not trick_or_treating

clean_data1 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "No") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(avg_age = mean(age))
  
```


```{r}
# number of people not trick_or_treating

clean_data1 %>% 
  group_by(year_id, age) %>% 
  filter(trick_or_treating == "No") %>% 
  summarise(count = n()) %>% 
  #group_by(year_id) %>% 
  ungroup() %>% 
  summarise(count = nrow(.))
```

```{r}
# checking if missing any ages

clean_data1 %>% 
  group_by(year_id, age) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  summarise(count = nrow(.))
  
  
  
  
```
data 1 had 5630 rows before turning age to numeric. Diff between data1(5630) - clean_data1(5334) = 296



```{r}
names(clean_data1)
```

```{r}
#patten <- 

clean_data1 %>% 
  select(age) %>% 
  str_detect("[A-Za-z]+")
```


```{r}
# Only Joy, Despair or NA in 2015

clean_data1 %>% 
  group_by(sweets, rating) %>% 
  #filter(rating = is.na()) %>% 
  summarise(count = n()) #%>% 
  #group_by(year_id) %>% 
  # ungroup() %>% 
  # summarise(count = nrow(.))
```

```{r}
test_data1 <- data1 %>% 
                clean_names() %>% 
                mutate(id = row_number(),
                       year = "2015") %>% 
                unite("year_id", year, id) %>% 
                pivot_longer(7:106,
                             names_to = "sweets",
                             values_to = "rating") %>% 
                rename("age" = "how_old_are_you",
                       "trick_or_treating" = 
                "are_you_going_actually_going_trick_or_treating_yourself") %>% 
                select(year_id, age, trick_or_treating, sweets, rating)
```


```{r}
# Age question inputs

test_data1 %>% 
  group_by(year_id, age) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(age) %>% 
  summarise(count = n())
```


```{r}
# Age question inputs after cleaning

clean_data1 %>% 
  group_by(year_id, age) %>%
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(age) %>% 
  summarise(count = n())
```



```{r}
write_csv(clean_data1, "data/data_cleaned_2015.csv")
```




